"""產生 start_form.vbs（用本機實際路徑，隱藏視窗）並放進 Windows「啟動」資料夾，
讓回填表單開機自動常駐。Windows 專用。

用法： python install_autostart.py
移除： 到啟動資料夾刪掉 start_form.vbs（執行後會印出路徑）。
"""
from __future__ import annotations

import os
import shutil
import sys
from pathlib import Path

BASE = Path(__file__).resolve().parent
py = BASE / ".venv" / "Scripts" / "python.exe"
if not py.exists():
    py = Path(sys.executable)

vbs = BASE / "start_form.vbs"
vbs.write_text(
    "' Auto-generated by install_autostart.py — 啟動 PSMF 回填表單（隱藏視窗）。\r\n"
    "Dim sh\r\n"
    'Set sh = CreateObject("WScript.Shell")\r\n'
    f'sh.CurrentDirectory = "{BASE}"\r\n'
    f'sh.Run """{py}"" form.py", 0, False\r\n',
    encoding="utf-8",
)

startup = Path(os.environ["APPDATA"]) / "Microsoft/Windows/Start Menu/Programs/Startup"
shutil.copy(vbs, startup / "start_form.vbs")
print(f"✅ 已產生 {vbs}")
print(f"✅ 已安裝開機自動啟動： {startup / 'start_form.vbs'}")
print("   下次登入會自動啟動回填表單；現在可手動雙擊 start_form.vbs 立即啟動。")
